# Generated by Django 5.1.6 on 2025-03-03 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_courses', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(related_name='groups', to='app_users.worker'),
        ),
        migrations.AddField(
            model_name='grouphomework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='homeworks', to='app_courses.group'),
        ),
        migrations.AddField(
            model_name='table',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tables', to='app_courses.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='app_courses.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tables', to='app_courses.tabletype'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='topics', to='app_courses.course'),
        ),
        migrations.AddField(
            model_name='grouphomework',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='homeworks', to='app_courses.topic'),
        ),
    ]
